version: "3"
services:
  nginx:
    depends_on:
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    container_name: api-container
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=shift-db
      - POSTGRES_PASSWORD=qNcy&uLf!2n^4##a
      - POSTGRES_PORT=5432
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - node_modules_volume:/app/node_modules
      - ./client:/app
volumes:
    node_modules_volume: